language: generic

os: osx


before_install: 
  - source $TRAVIS_BUILD_DIR/.travis/common.sh
  - ./.travis/setup.sh

install:
        - ./.travis/install.sh

jobs:
    include:
        #     - stage: "IceStorm"
        #env:
        #- PACKAGE=icestorm
        #- stage: "iVerilog"
        #env:
        #- PACKAGE=iverilog
     - stage: "Verilator"
       env:
       - PACKAGE=verilator
     - stage: "nextpnr"
       env:
       - PACKAGE=nextpnr

script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh
  - ls "$CONDA_PREFIX"/conda-bld/$TRAVIS_OS_NAME-64/*bz2

addons:
    homebrew:
        packages:
            - md5sha1sum


after_success:
  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u rjeschmi -l main $CONDA_PREFIX/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE-*.tar.bz2 --force

after_failure:
  - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh
