language: generic

os: osx


before_install: 
  - source $TRAVIS_BUILD_DIR/.travis/common.sh
  - git submodule update --init --remote --recursive
  - cd conda-hdmi2usb-packages && git checkout osx-add && cd ..

env:
    global:
        - MACOSX_DEPLOYMENT_TARGET=10.9
        - CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
        - OPT="--prefix=$HOME/test/prefix"


jobs:
    include:
     - stage: "IceStorm"
       env:
       - PACKAGE=icestorm
     - stage: "iVerilog"
       env:
       - PACKAGE=iverilog
     - stage: "Verilator"
       env:
       - PACKAGE=verilator
     - stage: "nextpnr"
       env:
       - PACKAGE=nextpnr

script:
  - source ./.travis/conda-ci install $OPT
  - echo CONDA_PREFIX is "$CONDA_PREFIX"
  - conda list
  - source ./.travis/conda-ci install-conda-build
  - conda list
  - conda build conda-hdmi2usb-packages/$PACKAGE
  - ls "$CONDA_PREFIX"/conda-bld/$TRAVIS_OS_NAME-64/*bz2

addons:
    homebrew:
        packages:
            - md5sha1sum


after_success:
  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u rjeschmi -l nightly $CONDA_PREFIX/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE-*.tar.bz2 --force

