language: generic

os: osx
osx_image: xcode6.4


before_install: 
  - git submodule update --init --remote --recursive
  - rsync -av conda-hdmi2usb-packages/* .


env:
    global:
        - MACOSX_DEPLOYMENT_TARGET=10.9
        - CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"


jobs:
    include:
     - stage: "Verilog Tools"
       env:
       - PACKAGE=icestorm
     - stage: "Verilog Tools"
       env:
       - PACKAGE=nextpnr

script:
  - script:
# install conda
  - source conda-ci install $OPT
  - echo CONDA_PREFIX is "$CONDA_PREFIX"
  - conda list
  - source conda-ci install-conda-build
  - conda list
# build test recipe
  - conda build recipe
  - ls "$CONDA_PREFIX"/conda-bld/$TRAVIS_OS_NAME-64/testme*bz2

addons:
    homebrew:
        packages:
            - md5sha1sum
