language: generic

os: osx


before_install: 
  - git submodule update --init --remote --recursive
  

env:
    global:
        - MACOSX_DEPLOYMENT_TARGET=10.9
        - CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
        - OPT="--prefix=$HOME/test/prefix"


jobs:
    include:
     - stage: "Verilog Tools"
       env:
       - PACKAGE=icestorm
     - stage: "Verilog Tools"
       env:
       - PACKAGE=nextpnr

script:
  - source ./.travis/conda-ci install $OPT
  - echo CONDA_PREFIX is "$CONDA_PREFIX"
  - conda list
  - source ./.travis/conda-ci install-conda-build
  - conda list
# build test recipe
  - conda build conda-hdmi2usb-packages/$PACKAGE
  - ls "$CONDA_PREFIX"/conda-bld/$TRAVIS_OS_NAME-64/testme*bz2

addons:
    homebrew:
        packages:
            - md5sha1sum
