language: generic

os: osx


before_install: 
  - source $TRAVIS_BUILD_DIR/.travis/common.sh
  - ./.travis/setup.sh

install:
        - ./.travis/install.sh
        - source $TRAVIS_BUILD_DIR/.travis/common.sh

jobs:
    include:
     - stage: "IceStorm"
       env:
       - PACKAGE=icestorm
     - stage: "iVerilog"
       env:
       - PACKAGE=iverilog
     - stage: "Verilator"
       env:
       - PACKAGE=verilator
     - stage: "nextpnr"
       env:
       - PACKAGE=nextpnr

script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh

addons:
    homebrew:
        packages:
            - md5sha1sum


after_success:
  - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

after_failure:
  - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh
