language: generic

os: osx


before_install: 
  - git submodule update --init --remote --recursive
  - cd conda-hdmi2usb-packages && git checkout osx-add && cd ..

env:
    global:
        - MACOSX_DEPLOYMENT_TARGET=10.9
        - CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
        - OPT="--prefix=$HOME/test/prefix"


jobs:
    include:
     - stage: "Libraries"
       env:
       - PACKAGE=isl
     - stage: "Libraries"
       env:
       - PACKAGE=libusb

script:
  - source ./.travis/conda-ci install $OPT
  - echo CONDA_PREFIX is "$CONDA_PREFIX"
  - conda list
  - source ./.travis/conda-ci install-conda-build
  - conda list
  - conda build conda-hdmi2usb-packages/$PACKAGE
  - ls "$CONDA_PREFIX"/conda-bld/$TRAVIS_OS_NAME-64/*bz2
  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l nightly $$CONDA_PREFIX/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE-`date +%Y.%m.%d`-0.tar.bz2 --force

addons:
    homebrew:
        packages:
            - md5sha1sum


after_success:
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash ./.travis/conda_upload.sh

